version: '2'
services:
  nginx:
    build: ./dockerconf/nginx
    container_name: myapp-nginx
    depends_on:
      - php
    volumes:
      - .:/var/www
    env_file: .env
    restart: always
  php:
    build: ./dockerconf/php
    container_name: myapp-php
    volumes:
      - .:/var/www
    restart: always

networks:
  default:
    external:
      name: nginxproxy_default
